spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/text
    username: root
    password: 61311
    type: com.mchange.v2.c3p0.ComboPooledDataSource
pagehelper:
  helper-dialect: mysql
